### ISSUE TITLE
multi_scan doesn't retry if xcpretty fails

### ISSUE THREAD

**Issue by Cyberbeni** [lyndsey-ferguson/fastlane-plugin-test_center#83] opened 2018-11-08 13:30 UTC
### New Issue Checklist

- [ ] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

### Issue Description

I'm trying to run UI tests on macOS 10.12 with Xcode 9.2 (and 10.13/14 with Xcode 10 but that's working fine) but the xcpretty version in fastlane doesn't generate any output, so I have to use the trainer fastlane plugin to convert the plist to xml test reports but this also means that the failed tests won't get retried.

##### Complete output when running fastlane, including the stack trace and command used

I think the provided information is enough to fix the issue but tell me if you need logs and I'll look through them to remove any sensitive info before posting.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                               |
| --------------------------- | ----------------------------------------------------------------------------------- |
| OS                          | 10.12.6                                                                             |
| Ruby                        | 2.3.8                                                                               |
| Bundler?                    | true                                                                                |
| Git                         | git version 2.10.0                                                                  |
| Installation Source         | ~/jenkins/git/applegui/JenkinsScripts/gui/apple-common/gems/ruby/2.3.0/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G29)                                                            |
| Ruby Lib Dir                | /usr/local/Cellar/ruby@2.3/2.3.8/lib                                                |
| OpenSSL Version             | OpenSSL 1.0.2p  14 Aug 2018                                                         |
| Is contained                | false                                                                               |
| Is homebrew                 | false                                                                               |
| Is installed via Fabric.app | false                                                                               |
| Xcode Path                  | /Applications/Xcode92.app/Contents/Developer/                                       |
| Xcode Version               | 9.2                                                                                 |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

desc "Description of what the lane does"
lane :run_built_tests do |options|
  multi_scan(
    workspace: options[:workspace],
    scheme: options[:scheme],
    try_count: 3,
    fail_build: false,
    output_types: 'junit',
    output_files: options[:junit_report_path],
    result_bundle: options[:result_bundle_path],
    output_directory: options[:result_bundle_path],
    derived_data_path: options[:derived_data_path],
    buildlog_path: options[:buildlog_path],
    destination: options[:destination],
    test_without_building: true
  )
end

lane :export_testresult do |options|
  trainer(
    output_directory: options[:result_bundle_path],
    fail_build: false,
    extension: '.xml',
    path: options[:test_result_path]
  )
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.107.0 | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status      |
| --------------------------- | ------- | ------------------ |
| fastlane-plugin-test_center | 3.5.8   | 🚫 Update available |
| fastlane-plugin-trainer     | 0.4.0   | ✅ Up-To-Date       |

<details><summary><b>Loaded gems</b></summary>

| Gem                         | Version      |
| --------------------------- | ------------ |
| did_you_mean                | 1.0.0        |
| bundler                     | 1.17.1       |
| CFPropertyList              | 3.0.0        |
| public_suffix               | 2.0.5        |
| addressable                 | 2.5.2        |
| atomos                      | 0.1.3        |
| babosa                      | 1.0.2        |
| claide                      | 1.0.2        |
| colored                     | 1.2          |
| colored2                    | 3.1.2        |
| highline                    | 1.7.10       |
| commander-fastlane          | 4.4.6        |
| declarative                 | 0.0.10       |
| declarative-option          | 0.1.0        |
| unf_ext                     | 0.0.7.5      |
| unf                         | 0.1.4        |
| domain_name                 | 0.5.20180417 |
| dotenv                      | 2.5.0        |
| emoji_regex                 | 0.1.1        |
| excon                       | 0.62.0       |
| multipart-post              | 2.0.0        |
| faraday                     | 0.15.3       |
| http-cookie                 | 1.0.3        |
| faraday-cookie_jar          | 0.0.6        |
| faraday_middleware          | 0.12.2       |
| fastimage                   | 2.1.4        |
| gh_inspector                | 1.1.3        |
| jwt                         | 2.1.0        |
| memoist                     | 0.16.0       |
| multi_json                  | 1.13.1       |
| os                          | 1.0.0        |
| signet                      | 0.11.0       |
| googleauth                  | 0.6.7        |
| httpclient                  | 2.8.3        |
| mime-types-data             | 3.2018.0812  |
| mime-types                  | 3.2.2        |
| uber                        | 0.1.0        |
| representable               | 3.0.4        |
| retriable                   | 3.1.2        |
| google-api-client           | 0.23.9       |
| json                        | 2.1.0        |
| mini_magick                 | 4.5.1        |
| multi_xml                   | 0.6.0        |
| plist                       | 3.4.0        |
| rubyzip                     | 1.2.2        |
| security                    | 0.1.3        |
| naturally                   | 2.2.0        |
| simctl                      | 1.6.5        |
| slack-notifier              | 2.3.2        |
| terminal-notifier           | 1.8.0        |
| unicode-display_width       | 1.4.0        |
| terminal-table              | 1.8.0        |
| tty-screen                  | 0.6.5        |
| tty-cursor                  | 0.6.0        |
| tty-spinner                 | 0.8.0        |
| word_wrap                   | 1.0.0        |
| nanaimo                     | 0.2.6        |
| xcodeproj                   | 1.7.0        |
| rouge                       | 2.0.7        |
| xcpretty                    | 0.3.0        |
| xcpretty-travis-formatter   | 1.0.0        |
| xctest_list                 | 1.1.6        |
| fastlane-plugin-test_center | 3.5.8        |
| trainer                     | 0.8.0        |
| fastlane-plugin-trainer     | 0.4.0        |
</details>

*generated on:* **2018-11-08**
</details>

**Comment by lyndsey-ferguson** [comment] 2018-11-08 13:38
Thanks for the report @Cyberbeni. I have a couple of issues that I am looking into and little time to do so. Can you include a sample project with the failing tests with a fastfile and gemfile that use trainer?

**Comment by lyndsey-ferguson** [comment] 2018-11-11 18:54
@Cyberbeni you're using the parallelization feature of Xcode 10?

**Comment by Cyberbeni** [comment] 2018-11-11 19:11
There is no parallelization for macOS testing. First I'm build-for-testing the app and the test with Xcode 10 then I'm also build-for-testing the test only (different scheme, same files, swift 4.0 instead of swift 4.2, no test app) with Xcode 9.2 then I copy over the whole stuff to macOS 10.12 and run the tests with Xcode 9.2 (Xcode 10 built app with everything from the Xcode 9.2 build copied over to the same derived data build products folder)

This should be the same as just doing the whole stuff with Xcode 9.2 (the latest version that can run on macOS 10.12)

I'll also need to do this with macOS 10.11 and Xcode 8.2

**Comment by lyndsey-ferguson** [comment] 2018-11-11 22:03
From what I understand of the problem you are facing, the summary:
1. Xcode 9.2 on Mac OS 10.12, combined with `xcpretty` fails to generate junit.xml files. Yes? What happens?
2. Xcode 10 on Mac OS 10.13, combined with `xcpretty` generates the junit.xml file without problem. Yes?

**Comment by lyndsey-ferguson** [comment] 2018-11-11 22:04
If the above no. 1 is true, do you have a feeling for why this happens? I have been using Xcode 9.2 with OS 10.12 without issues. Do you believe that this is an issue with Mac apps?

**Comment by Cyberbeni** [comment] 2018-11-12 08:59
We also have a common framework for the iOS and Mac tests using this method: https://stackoverflow.com/a/35102636
This can be seen on the Xcode 9.2 output having 0 tests but not on the Xcode 10 output. I copied the start of the log from both as the rest doesn't seem to have any difference.

Xcode 9.2:
```
xcodebuild -workspace ~/jenkins/git/applegui/MyApp/MyApp.xcworkspace -scheme MyAppMac -derivedDataPath ~/jenkins/workspace/Mac-Run-Built-TestSuite/DerivedData/ -resultBundlePath ~/asd2 test-without-building
User defaults from command line:
    IDEBuildOperationResultBundlePath = /Users/jenkins/asd2
    IDEDerivedDataPathOverride = /Users/jenkins/jenkins/workspace/Mac-Run-Built-TestSuite/DerivedData

2018-11-12 09:36:06.973 xcodebuild[54401:6847800]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/var/folders/82/nhc_n50d0yx5pck54wn97_l40000gp/T/com.apple.dt.XCTest/IDETestRunSession-B9279F35-E693-44F5-BADD-87C8EE6755D9/MyAppMacUITests-3FD3C9EE-B227-432D-BC06-EA5CCA57BD19/Session-MyAppMacUITests-2018-11-12_093606-Vac7iO.log
2018-11-12 09:36:06.973 xcodebuild[54401:6847797] [MT] IDETestOperationsObserverDebug: (7E72458A-BD5B-4ACD-8451-609DBAE3D415) Beginning test session MyAppMacUITests-7E72458A-BD5B-4ACD-8451-609DBAE3D415 at 2018-11-12 09:36:06.973 with Xcode 9C40b on target <DVTLocalComputer: 0x7fadbbc0bb10 (My Mac | x86_64)> (10.12.6 (16G29))
2018-11-12 09:36:07.301792+0100 MyAppMacUITests-Runner[54407:6847929] Running tests...
2018-11-12 09:36:07.392 xcodebuild[54401:6847926]  IDETestOperationsObserverDebug: (7E72458A-BD5B-4ACD-8451-609DBAE3D415) OS X: Failure requesting crash reports in /Library/Logs/DiagnosticReports: Error Domain=com.apple.dt.Xcode.IDETesting.OSXCrashReportObserverError Code=3 "Could not open /Library/Logs/DiagnosticReports for O_EVTONLY: 13 - Permission denied" UserInfo={NSLocalizedDescription=Could not open /Library/Logs/DiagnosticReports for O_EVTONLY: 13 - Permission denied}
Test Suite 'All tests' started at 2018-11-12 09:36:07.412
Test Suite 'TestUtilsMac.framework' started at 2018-11-12 09:36:07.413
Test Suite 'TestUtilsMac.framework' passed at 2018-11-12 09:36:07.413.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'MyAppMacUITests.xctest' started at 2018-11-12 09:36:07.413
```
Xcode 10:
```
xcodebuild -workspace MyApp/MyApp.xcworkspace -scheme MyAppMac -derivedDataPath DerivedData -resultBundlePath asd2 test-without-building
User defaults from command line:
    IDEBuildOperationResultBundlePath = /Users/benedek.kozma/Desktop/dev/applegui-2/asd2
    IDEDerivedDataPathOverride = /Users/benedek.kozma/Desktop/dev/applegui-2/DerivedData

Testing started on 'My Mac'
2018-11-12 09:38:37.047 xcodebuild[12315:8578204]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/benedek.kozma/Desktop/dev/applegui-2/asd2/1_Test/Diagnostics/MyAppMacUITests-94E95CAB-DDFE-472F-9F25-5FCEE1474743/MyAppMacUITests-CCFE5F39-A169-43EC-A18A-260C00285E36/Session-MyAppMacUITests-2018-11-12_093837-ly0upS.log
2018-11-12 09:38:37.047 xcodebuild[12315:8578196] [MT] IDETestOperationsObserverDebug: (0AADDCA3-FBE2-4274-8563-DA238A1502C8) Beginning test session MyAppMacUITests-0AADDCA3-FBE2-4274-8563-DA238A1502C8 at 2018-11-12 09:38:37.047 with Xcode 10A255 on target <DVTLocalComputer: 0x7ff8c3663bc0 (My Mac | x86_64h)> (10.14 (18A389))
2018-11-12 09:38:37.574498+0100 MyAppMacUITests-Runner[12320:8578337] Running tests...
Test Suite 'All tests' started at 2018-11-12 09:38:37.980
Test Suite 'MyAppMacUITests.xctest' started at 2018-11-12 09:38:37.980
```

**Comment by lyndsey-ferguson** [comment] 2018-11-21 14:14
@Cyberbeni could you provide me a sample project that exhibits the problem? I need help as I'm juggling several priorities. I am certain once I can see the problem, it will be easy to resolve.

**Comment by Cyberbeni** [comment] 2018-11-26 17:00
I tried creating a dummy project and add UI test to it where my UI tests are subclassing from a framework that's weakly linked against XCTest but in this case XCPretty could properly generate output from it while the output has the same format without it as before.

**Comment by lyndsey-ferguson** [comment] 2018-11-26 18:13
If you can find a way to incrementally get your sample project to be closer to the failing project, and then provide me with that sample project, it will go a long way to getting this resolved.

**Comment by Cyberbeni** [comment] 2018-11-30 18:11
Sadly I couldn't break the sample project yet.

One possible fix would be to use trainer to generate the report in testrun_info if there is no file found on report_filepath, what do you think?

**Comment by lyndsey-ferguson** [comment] 2018-11-30 18:17
Hm. Unless I can reproduce and fix it properly for everyone, I don't  want to add an external dependency such as trainer. I'm considering closing this issue for now.

**Comment by lyndsey-ferguson** [comment] 2019-03-17 17:17
Closing this issue as there has not been any activity since November. If a sample project can be generated, please open a new issue.

**Closed by lyndsey-ferguson** 2019-03-17 17:17 UTC
Labels: ♻️ multi_scan, 🔎 under investigation
