### ISSUE TITLE
Collate json reports action fails

### ISSUE THREAD

**Issue by jineshqa** [lyndsey-ferguson/fastlane-plugin-test_center#163] opened 2019-10-28 03:17 UTC
### New Issue Checklist

- [X] Updated `fastlane-plugin-test_center` to the latest version
- [X] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [X] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [X] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

### Issue Description

I am using collate_json_reports to collate various json files generated from xcresult files by using xcresulttool.

##### Complete output when running fastlane, including the stack trace and command used

<details>

```
Traceback (most recent call last):
	31: from /Users/jdoshi/.rbenv/versions/2.6.3/bin/fastlane:23:in `<main>'
	30: from /Users/jdoshi/.rbenv/versions/2.6.3/bin/fastlane:23:in `load'
	29: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/bin/fastlane:23:in `<top (required)>'
	28: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	27: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	26: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	25: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	24: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	23: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	22: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	21: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	20: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	19: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	18: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	17: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	16: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	15: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	14: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	13: from Fastfile:562:in `block (2 levels) in parsing_binding'
	12: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	11: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	10: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	 9: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	 8: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	 7: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 6: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-2.134.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	 5: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.8.12/lib/fastlane/plugin/test_center/actions/collate_json_reports.rb:12:in `run'
	 4: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.8.12/lib/fastlane/plugin/test_center/actions/collate_json_reports.rb:12:in `each'
	 3: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.8.12/lib/fastlane/plugin/test_center/actions/collate_json_reports.rb:15:in `block in run'
	 2: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.8.12/lib/fastlane/plugin/test_center/actions/collate_json_reports.rb:24:in `merge_reports'
	 1: from /Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.8.12/lib/fastlane/plugin/test_center/actions/collate_json_reports.rb:24:in `each_key'
/Users/jdoshi/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/fastlane-plugin-test_center-3.8.12/lib/fastlane/plugin/test_center/actions/collate_json_reports.rb:26:in `block in merge_reports': [!] undefined method `concat' for {"_name"=>"ActionsInvocationRecord"}:Hash (NoMethodError)
Did you mean?  count
Did you mean?  count

```
</details>

Please let me know if this is not enough and you need sample json file.

**Comment by lyndsey-ferguson** [comment] 2019-10-28 13:09
@jineshqa yes please provide sample sample json files. The ones I have work fine and I need to test the collate json action on to identify the problem. 👍 Thanks!

**Comment by lyndsey-ferguson** [comment] 2019-11-05 19:15
@jineshqa any update on providing sample json files?

**Comment by lyndsey-ferguson** [comment] 2019-11-09 16:31
Closing this issue as I cannot reproduce and there hasn't been any activity on this Issue.

Will re-open if given sample files that I can use to reproduce the issue.

**Closed by lyndsey-ferguson** 2019-11-09 16:31 UTC
Labels: 🐞bug, 🔎 under investigation, 🙏 help wanted
