### ISSUE TITLE
NoMethodError: [!] undefined method 'value' for nil:NilClass error after multi_scan completes on CircleCI

### ISSUE THREAD

**Issue by hellostu** [lyndsey-ferguson/fastlane-plugin-test_center#194] opened 2020-02-21 10:54 UTC
### Question Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I searched for [existing GitHub issues](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/issues)

### Question Subject
`NoMethodError: [!] undefined method 'value' for nil:NilClass` error after multi_scan completes on CircleCI

#### Question Description
Hello! Thanks for the work put into this project. It's really helpful! I keep hitting this issue when running multi_scan on CircleCI. My fastfile contains the following:

```
default_platform(:ios)

platform :ios do

  before_all do
    setup_circle_ci
  end

  lane :tests do
    multi_scan(
        scheme: "...",
	include_simulator_logs: false,
	try_count: 3, # retry _failing_ tests up to three times^1. 
  	fail_build: false,
  	parallel_testrun_count: 3,
        devices: ["iPhone 11"]
    )
  end
end
```

The following error occurs after multi_scan has completed and passed:

```
NoMethodError: [!] undefined method `value' for nil:NilClass
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/helper/html_test_report.rb:242:in `failure_details'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/helper/html_test_report.rb:187:in `block in remove_duplicate_testcases'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/helper/html_test_report.rb:186:in `each'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/helper/html_test_report.rb:186:in `remove_duplicate_testcases'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/helper/html_test_report.rb:25:in `each'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/helper/html_test_report.rb:25:in `collate_report'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/actions/collate_html_reports.rb:14:in `block in run'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/actions/collate_html_reports.rb:13:in `each'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/actions/collate_html_reports.rb:13:in `run'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/helper/multi_scan_manager/report_collator.rb:89:in `collate_html_reports'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/helper/multi_scan_manager/report_collator.rb:29:in `collate'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:250:in `collate_batched_reports_for_testable'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:198:in `block in collate_batched_reports'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:197:in `each'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:197:in `collate_batched_reports'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:179:in `run_test_batches'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:70:in `run'
  /Users/distiller/react-native-coda-player/native-lib/ios/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-test_center-3.9.0.beta.3/lib/fastlane/plugin/test_center/actions/multi_scan.rb:42:in `run'
```

I'd really appreciate some help with this!

Thanks

**Comment by lyndsey-ferguson** [comment] 2020-02-21 14:39
It is having a problem collating html. As I don't have time to fix this in this moment, set `output_types: junit` to avoid generating the HTML report.

**Comment by lyndsey-ferguson** [comment] 2020-02-21 14:40
Can you reproduce this problem on your local computer? If you can provide me a sample project/Fastfile that duplicates this problem, it will be a lot easier for me to fix this.

**Comment by lyndsey-ferguson** [comment] 2020-03-11 22:02
Closing due to an inability to reproduce/debug

**Closed by lyndsey-ferguson** 2020-03-11 22:02 UTC
Labels: Consider closing Friday, ♻️ multi_scan, 🐞bug, 🔶 collate_html_reports, 🙏 help wanted
