### ISSUE TITLE
Multi scan runs all the disabled tests in the scheme

### ISSUE THREAD

**Issue by sneha-je** [lyndsey-ferguson/fastlane-plugin-test_center#103] opened 2019-06-09 17:04 UTC
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

### Issue Description
I have a bunch of UI tests disabled in my test scheme. Scan runs only the enabled tests in the scheme. But, when I used multi_scan, it passed all the tests in the scheme including the disabled ones to the "test_only" parameter. 

Would be great if mult_scan would only run the tests that are enabled in the scheme

NOTE: I assumed that multi_scan runs the first iteration of tests and reruns if tests fail. Or, should I first run my tests using scan and pass the results to multi_scan to rerun only the tests that failed in the testrun by scan ?

**Comment by lyndsey-ferguson** [comment] 2019-06-09 17:49
`multi_scan` is supposed to skip the tests that have been disabled in the Scheme. Can you provide a log so I can take a look at what is going on? 

Remember to please remove any sensitive data before posting.

**Comment by MarianoRappazzo** [comment] 2019-06-12 20:24
I have the same problem here, all UI Tests from the project runs even if the scheme disabled some of them.

**Comment by lyndsey-ferguson** [comment] 2019-06-13 13:18
@MarianoRappazzo since @sneha-je has not posted a log, would you be able to?

Also would you be able to try the previous version of the plugin? You can do so by modifying your `Pluginfile` per my instructions below, run `bundle install`, and then run your fastlane again?

Pluginfile:
```
gem 'fastlane-plugin-test_center', '3.6.3'
```

**Comment by lyndsey-ferguson** [comment] 2019-06-13 13:25
Also, can you re-run your fastlane with the `--verbose` option and include _that_ log

**Comment by lyndsey-ferguson** [comment] 2019-06-17 23:15
Can you provide the logs that I requested? I'll go ahead and close this Issue on Friday (EST) if there are no logs to provide.

**Comment by lyndsey-ferguson** [comment] 2019-06-20 16:53
Remember, I will close this Issue tomorrow unless you can provide me with logs. Please use the `--verbose` flag. BTW, I have confirmed that this works with the current feature that I am working on for parallel test runs. If you would like to use that beta, please see this [pull request](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/pull/104)

**Comment by sneha-je** [comment] 2019-06-21 13:35
Sorry for the late reply. When I run the example tests in this repo by disabling one of the UI tests, the disabled one didn't run.

I'm using "workspace" in my fastfile scan instead of "project" as used in this project's fastfile. I initially thought that might be the issue but that isn't the case. I'm checking what is so different in my work project's setup that it's running all the disabled ones as well. 

Here is the log I've removed all the compiling logs and test cases names
`bundle exec fastlane sweep
[✔] 🚀 
+-----------------------------+---------+----------------------------------------------------------------------------------+
|                                                       Used plugins                                                       |
+-----------------------------+---------+----------------------------------------------------------------------------------+
| Plugin                      | Version | Action                                                                           |
+-----------------------------+---------+----------------------------------------------------------------------------------+
| fastlane-plugin-versioning  | 0.3.4   | get_version_number_from_git_branch get_version_number_from_plist                 |
|                             |         | get_build_number_from_plist ci_build_number increment_version_number_in_plist    |
|                             |         | get_app_store_version_number get_info_plist_path increment_build_number_in_plist |
| fastlane-plugin-test_center | 3.7.0   | suppressed_tests suppress_tests suppress_tests_from_junit tests_from_xctestrun   |
|                             |         | collate_test_result_bundles tests_from_junit multi_scan collate_html_reports     |
|                             |         | collate_junit_reports collate_json_reports                                       |
+-----------------------------+---------+----------------------------------------------------------------------------------+

[12:50:55]: ------------------------------
[12:50:55]: --- Step: default_platform ---
[12:50:55]: ------------------------------
[12:50:55]: Driving the lane 'ios sweep' 🚀
[12:50:55]: ------------------------
[12:50:55]: --- Step: multi_scan ---
[12:50:55]: ------------------------

+----------------------+----------------------+
| Summary for multi_scan (test_center v3.7.0) |
+----------------------+----------------------+
| try_count            | 3                    |
| fail_build           | false                |
+----------------------+----------------------+

[12:50:55]: Successfully loaded '/fastlane/Scanfile' 📄

+----------------------+---------------------+
| Detected Values from './fastlane/Scanfile' |
+----------------------+---------------------+
| clean                | true                |
+----------------------+---------------------+

[12:50:55]: $ xcodebuild -showBuildSettings -workspace /test.xcworkspace -scheme test
[12:50:58]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[12:51:04]: Successfully loaded '/fastlane/Scanfile' 📄

+----------------------+---------------------+
| Detected Values from './fastlane/Scanfile' |
+----------------------+---------------------+
| clean                | true                |
+----------------------+---------------------+

[12:51:04]: $ xcodebuild -showBuildSettings -workspace /test.xcworkspace -scheme test
[12:51:07]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...

+------------------------------------------------+---------------------------------------------------------------------------------------------+
|                                                           Summary for scan 2.125.2                                                           |
+------------------------------------------------+---------------------------------------------------------------------------------------------+
| workspace                                      | /test.xcworkspace                                          |
| fail_build                                     | false                                                                                       |
| scheme                                         | test                                                                       |
| device                                         | iPad Pro (12.9-inch) (12.2)                                                                 |
| build_for_testing                              | true                                                                                        |
| derived_data_path                              | /Library/Developer/Xcode/DerivedData/geondiajzwenclw |
| skip_detect_devices                            | false                                                                                       |
| force_quit_simulator                           | false                                                                                       |
| reset_simulator                                | false                                                                                       |
| reinstall_app                                  | false                                                                                       |
| app_identifier                                 | com.test                                                                    |
| clean                                          | true                                                                                        |
| open_report                                    | false                                                                                       |
| output_directory                               | ./fastlane/test_output                                                                      |
| output_types                                   | html,junit                                                                                  |
| buildlog_path                                  | ~/Library/Logs/scan                                                                         |
| include_simulator_logs                         | false                                                                                       |
| should_zip_build_products                      | false                                                                                       |
| result_bundle                                  | false                                                                                       |
| use_clang_report_name                          | false                                                                                       |
| disable_concurrent_testing                     | false                                                                                       |
| skip_build                                     | false                                                                                       |
| slack_use_webhook_configured_username_and_icon | false                                                                                       |
| slack_username                                 | fastlane                                                                                    |
| slack_icon_url                                 | https://s3-eu-west-1.amazonaws.com/fastlane.tools/fastlane.png                              |
| skip_slack                                     | false                                                                                       |
| slack_only_on_failure                          | false                                                                                       |
| xcode_path                                     | /Applications/Xcode.app                                                                     |
+------------------------------------------------+---------------------------------------------------------------------------------------------+

[12:51:11]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace /test.xcworkspace -scheme test -destination 'platform=iOS Simulator,id=A2EC5C46-4A62-4E4C-BD10-AD2C176B5FAB' -derivedDataPath '/Library/Developer/Xcode/DerivedData/geondiajzwenclw' clean build-for-testing | tee '/Library/Logs/scan/test.log' | xcpretty  --report html --output '/fastlane/test_output/report.html' --report junit --output '/fastlane/test_output/report.junit' --report junit --output '/var/folders/51/43wsglzs2fz34fvq5rlnynq80000gp/T/junit_report20190621-60819-ladzyp' 
[12:51:11]: ▸ Loading...
[


Compiling  Logs

[13:02:13]: ▸ Running script 'Run Script'
[13:02:50]: ▸ Running script '[CP] Embed Pods Frameworks'
[13:03:14]: ▸ Running script '[CP] Copy Pods Resources'
[13:03:17]: Running Tests: ▸ Touching Tests.xctest
[13:03:17]: ▸ Signing /Library/Developer/Xcode/DerivedData/geondiajzwenclw/Build/Products/Debug-iphonesimulator/UI\ Tests-Runner.app/PlugIns/UI\ Tests.xctest
[13:03:29]: ▸ Signing /Library/Developer/Xcode/DerivedData/geondiajzwenclw/Build/Products/Debug-iphonesimulator/UI\ Tests-Runner.app
[13:03:32]: ▸ Test build Succeeded
+--------------------+---+
|      Test Results      |
+--------------------+---+
| Number of tests    | 0 |
| Number of failures | 0 |
+--------------------+---+

[13:03:36]: Successfully loaded '/fastlane/Scanfile' 📄

+----------------------+---------------------+
| Detected Values from './fastlane/Scanfile' |
+----------------------+---------------------+
| clean                | true                |
+----------------------+---------------------+

[13:03:36]: $ xcodebuild -showBuildSettings -workspace /test.xcworkspace -scheme test
[13:03:39]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
[13:03:46]: Successfully loaded '/fastlane/Scanfile' 📄

+----------------------+---------------------+
| Detected Values from './fastlane/Scanfile' |
+----------------------+---------------------+
| clean                | true                |
+----------------------+---------------------+

[13:03:46]: $ xcodebuild -showBuildSettings -workspace /test.xcworkspace -scheme test
[13:03:49]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...

+------------------------------------------------+----------------------------------------------------------------------------------------------------+
|                                                              Summary for scan 2.125.2                                                               |
+------------------------------------------------+----------------------------------------------------------------------------------------------------+
| workspace                                      | /test.xcworkspace                                                 |
| scheme                                         | test                                                                           |
| device                                         | iPad Pro (12.9-inch) (12.2)                                                                        |
| test_without_building                          | true                                                                                               |
| derived_data_path                              | /Library/Developer/Xcode/DerivedData/geondiajzwenclw        |
| skip_detect_devices                            | false                                                                                              |
| force_quit_simulator                           | false                                                                                              |
| reset_simulator                                | false                                                                                              |
| reinstall_app                                  | false                                                                                              |
| app_identifier                                 | com.test                                                                              |
| open_report                                    | false                                                                                              |
| buildlog_path                                  | ~/Library/Logs/scan                                                                                |
| include_simulator_logs                         | false                                                                                              |
| should_zip_build_products                      | false                                                                                              |
| result_bundle                                  | false                                                                                              |
| use_clang_report_name                          | false                                                                                              |
| disable_concurrent_testing                     | false                                                                                              |
| skip_build                                     | false                                                                                              |
| slack_use_webhook_configured_username_and_icon | false                                                                                              |
| slack_username                                 | fastlane                                                                                           |
| slack_icon_url                                 | https://s3-eu-west-1.amazonaws.com/fastlane.tools/fastlane.png                                     |
| skip_slack                                     | false                                                                                              |
| slack_only_on_failure                          | false                                                                                              |
| clean                                          | false                                                                                              |
| output_directory                               | ./fastlane/test_output                                                                             |
| only_testing                                   | ["<Listed all tests including the disabled ones>"]                                                            |
| output_types                                   | html,junit                                                                                         |
| output_files                                   | report.html,report.junit                                                                           |
| fail_build                                     | true                                                                                               |
| xcode_path                                     | /Applications/Xcode.app                                                                            |
+------------------------------------------------+----------------------------------------------------------------------------------------------------+

[13:03:56]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace /test.xcworkspace -scheme test -destination 'platform=iOS Simulator,id=A2EC5C46-4A62-4E4C-BD10-AD2C176B5FAB' -derivedDataPath '/Library/Developer/Xcode/DerivedData/geondiajzwenclw' -only-testing: "<Listed all tests including the disabled ones>" | tee '/Library/Logs/scan/test.log' | xcpretty  --report html --output '/fastlane/test_output/report.html' --report junit --output '/fastlane/test_output/report.junit' --report junit --output '/var/folders/51/43wsglzs2fz34fvq5rlnynq80000gp/T/junit_report20190621-60819-n4pq9q' 
[13:03:56]: ▸ Loading...
[13:04:01]: ▸ 2019-06-21 13:04:01.933 xcodebuild[71248:4330127]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
[13:04:01]: ▸ /Library/Developer/Xcode/DerivedData/Jgeondiajzwenclw/Logs/Test/Test-test-2019.06.21_1-04-01-+0100.xcresult/1_Test/Diagnostics/UI Tests-72935113-25A4-46B6-9848-C7F4D7080A5C/UI Tests-FA29E3AD-333A-4BA7-BA86-B60E14DDBAEA/Session-UI Tests-2019-06-21_10401 pm-I59f9t.log
[13:04:01]: ▸ 2019-06-21 13:04:01.933 xcodebuild[71248:4329892] [MT] IDETestOperationsObserverDebug: (7D19A5F4-3F31-4949-8C23-242548794272) Beginning test session UI Tests-7D19A5F4-3F31-4949-8C23-242548794272 at 2019-06-21 1:04:01.933 pm with Xcode 10E1001 on target <DVTiPhoneSimulator: 0x7f9a9b8bb490> {
[13:04:01]: ▸ SimDevice: iPad Pro (12.9-inch) (A2EC5C46-4A62-4E4C-BD10-AD2C176B5FAB, iOS 12.2, Shutdown)
[13:04:01]: ▸ } (12.2 (16E226))
[13:04:50]: ▸ 2019-06-21 13:04:50.219 xcodebuild[71248:4329892] [MT] IDETestOperationsObserverDebug: (7D19A5F4-3F31-4949-8C23-242548794272) Finished requesting crash reports. Continuing with testing.
[13:05:01]: ▸ Selected tests
[13:05:01]: ▸ Test Suite UI Tests.xctest started
`

**Comment by lyndsey-ferguson** [comment] 2019-06-23 14:31
I'm sorry, but this log doesn't provide information on what tests were run. I can understand if you do not want to provide highly sensitive information: each developer faces certain restrictions that cannot be explained.

Given that, can you please provide a sample Xcode project and `Fastfile` that calls `multi_scan` with that project so that I can debug this? As I wrote before, everything is currently working fine for me.

I can leave this Issue open until July 5th. I'll close the Issue on the 6th. You can always re-open the issue once you can provide the sample Xcode project and `Fastfile`.

**Comment by lyndsey-ferguson** [comment] 2019-07-06 20:05
I'm closing the issue as I cannot reproduce it, and I don't have enough information to debug it.

**Comment by kwstasna** [comment] 2019-09-09 12:25
We have the same issue.
Lots of tests are disabled in a specific suite, but multi_scan still tries to run everything.

**Comment by lyndsey-ferguson** [comment] 2019-09-09 17:22
@kwstasna yes, if you can provide an example project along with the Fastfile used to call `multi_scan` on it, I can re-open this Issue and begin investigating.

**Comment by rahulsharma2905** [comment] 2019-10-04 06:51
I have a repro for this issue, my scenario is i have 1 test scheme say 'scheme1' which was created in some previous version of xcode, and recently i created a new scheme 'scheme2' in xcode 10.2.

- When i run scheme1 with multi_scan, it runs all the tests regardless whatever i have defined in scheme1.

- When i run scheme2, it runs as expected.

So, I compared .xcsheme files of both schemes, and found that:

- scheme1 has a xml tag <SelectedTests> and all enabled tests are listed there.

- scheme2 has a xml tag <SkippedTests> and all disabled tests are listed there.

So, my guess is if "it will get use all the tests from the binary minus the skipped tests", then maybe for scheme1 as there are no SkippedTests, it is running all tests.

**Comment by lyndsey-ferguson** [comment] 2019-10-04 12:39
This is helpful. I've re-opened this Issue.

**Comment by lyndsey-ferguson** [comment] 2019-10-04 12:42
I may not be able to address this right away, but if you want to fork this repo and try fixing it, you can look in the [`tests_from_xctestrun`](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/lib/fastlane/plugin/test_center/actions/tests_from_xctestrun.rb#L22) action to make sure that the `test_identifiers` are the only ones that are passed in (rather than using `SkippedTests` to filter out tests).

**Comment by lyndsey-ferguson** [comment] 2019-10-06 19:11
`tests_from_xctestrun` uses the `xctestrun` file generated from a build to determine which tests to skip. I can only assume that that file for an older version of Xcode, an older version of `xctestrun` file has some sort of identifier that makes explicit which tests _are to run_. Can you provide a sample of the older generated `xctestrun`?

**Comment by rahulsharma2905** [comment] 2019-10-07 10:01
i can't provide a sample ```xctestrun```, but i did some changes in ```tests_from_xctestrun``` file and my observations are:

- xctestrun of schemes generated by XCode 11 have key ```SkipTestIdentifiers```, which you are currently using.

- xctestrun of schemes generated by old XCode does not have ```SkipTestIdentifiers```, but have another key ```OnlyTestIdentifiers```.

My changes seems to be working for me for both new and old schemes. 
Take a look at it: 
https://github.com/rahulsharma2905/fastlane-plugin-test_center/blob/master/lib/fastlane/plugin/test_center/actions/tests_from_xctestrun.rb#L28

**Comment by lyndsey-ferguson** [comment] 2019-10-09 13:07
@rahulsharma2905 thank you for the confirmation! If you're open to creating a PR with tests, I'd welcome it. I suggest that you check for `OnlyTestIdentifiers` before even pulling out the tests from the `XCTest` call. Here: https://github.com/rahulsharma2905/fastlane-plugin-test_center/blob/master/lib/fastlane/plugin/test_center/actions/tests_from_xctestrun.rb#L19

**Comment by bpoplauschi** [comment] 2019-10-22 11:01
Hi guys. Me and my team are having the same issue (`multi_scan` runs the disabled tests with the newer versions of the `test_center` plugin).

I'm glad @rahulsharma2905 shared those insights, but I think you only have half the picture.

From what I tested, the difference between having the `SelectedTests` tag in the `xcscheme` (backed by `OnlyTestIdentifiers` in the `xctestrun`) or `SkippedTests` tag in the `xcscheme` (backed by `SkipTestIdentifiers` in the `xctestrun`) sits in the `useTestSelectionWhitelist` option from each scheme (visually identifiable as Scheme Tests tab, Options... Automatically include new tests). See screenshot

![Screenshot 2019-10-22 at 13 57 47](https://user-images.githubusercontent.com/154913/67279573-f360e080-f4d3-11e9-8774-70abb9fe5968.png)

Setting this on / off back and forth, I saw the `xcscheme` change between the 2 tags mentioned above and consistent with the `xctestrun` tags.

So in my opinion, this is not directly influenced by the Xcode version (but it may be indirectly if Xcode 11 has the option default changed).

PS: glad to see #155 looking so close to being merged. 👍 

> I have a repro for this issue, my scenario is i have 1 test scheme say 'scheme1' which was created in some previous version of xcode, and recently i created a new scheme 'scheme2' in xcode 11.0.
> 
> * When i run scheme1 with multi_scan, it runs all the tests regardless whatever i have defined in scheme1.
> * When i run scheme2, it runs as expected.
> 
> So, I compared .xcsheme files of both schemes, and found that:
> * scheme1 has a xml tag <SelectedTests> and all enabled tests are listed there.
> * scheme2 has a xml tag <SkippedTests> and all disabled tests are listed there.
> 
> So, my guess is if "it will get use all the tests from the binary minus the skipped tests", then maybe for scheme1 as there are no SkippedTests, it is running all tests.
>
> i can't provide a sample xctestrun, but i did some changes in `tests_from_xctestrun` file and my observations are:
> `xctestrun` of schemes generated by XCode 11 have key `SkipTestIdentifiers`, which you are currently using.
> `xctestrun` of schemes generated by old XCode does not have `SkipTestIdentifiers`, but have another key `OnlyTestIdentifiers`.

**Comment by lyndsey-ferguson** [comment] 2019-10-22 17:26
@bpoplauschi thank you for educating us all, this is great knowledge!

**Closed** 2019-10-23 12:41 UTC
Labels: ☑️ tests_from_xctestrun, 🐞bug, 🐣good first issue, 🔨in-progress, 🙏 help wanted

**Comment by lyndsey-ferguson** [comment] 2019-10-23 12:45
Fixed in [v3.8.11](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/releases/tag/v3.8.11)

**Comment by bpoplauschi** [comment] 2019-10-23 13:06
We really appreciate this @lyndsey-ferguson and @rahulsharma2905 🎉

**Comment by lyndsey-ferguson** [comment] 2019-10-23 13:08
Yes, thank you for your contribution @rahulsharma2905 !!!!
