### ISSUE TITLE
xcov fails when running after multi_scan

### ISSUE THREAD

**Issue by slanska** [lyndsey-ferguson/fastlane-plugin-test_center#283] opened 2020-09-04 20:41 UTC
Hi there, First, thanks for the nice plugin.

While struggling with instability of UI tests I came across your plugin and replaced run_tests with multi_scan, using the following config (actual project name is replaced with Foo):

    _test_run_block = lambda do |testrun_info|
      sh('mkdir -p ./temp_build_logs')
      temporary_directory = "./temp_build_logs"
      
      require "fileutils"
      FileUtils.cp_r("#{Scan.config[:derived_data_path]}/Logs/Test", temporary_directory)
    end

    multi_scan(
      workspace: "Foo.xcworkspace", 
      scheme: 'testCoverage',
      try_count: 5, # retry _failing_ tests up to three times^1.
      fail_build: true,
      parallel_testrun_count: 1, # run subsets of your tests on parallel simulators^2
      slack_url: slack_url,
      output_types: "html,junit",
      collate_reports: true,
      testrun_completed_block: test_run_block,
      output_files: "./combine_test_report.html,./combine_test_report.junit",
    )

    xcov(
      workspace: "Foo.xcworkspace", 
      scheme: "testCoverage",
      output_directory: "fastlane/test_output/xcov_output/",
      slack_username: "fastlane",
      slack_url: slack_url,
      json_report: true,
      markdown_report: true,
      derived_data_path: "temp_build_logs/"
    )_

(Note that test_run_block was added as one of attempts to fix issue with xcov, according to https://www.mininny.dev/ios/testing-with-fastlane/ to handle multiple. It did not fix the xcov issue though). 

Since I started using multi_scan, I keep getting the following xcov error:

+-----------------------------+-------------------------------------------+
|                         Summary for xcov 1.7.2                          |
+-----------------------------+-------------------------------------------+
| workspace                   | Foo.xcworkspace                        |
| scheme                      | testCoverage                              |
| output_directory            | fastlane/test_output/xcov_output/         |
| slack_username              | fastlane                                  |
| json_report                 | true                                      |
| markdown_report             | true                                      |
| derived_data_path           | temp_build_logs/                          |
| html_report                 | true                                      |
| minimum_coverage_percentage | 0                                         |
| skip_slack                  | false                                     |
| slack_message               | Your *xcov* coverage report               |
| ignore_file_path            | ./fastlane/.xcovignore                    |
| include_test_targets        | false                                     |
| only_project_targets        | false                                     |
| disable_coveralls           | false                                     |
| ideFoundationPath           | /Applications/Xcode.app/Contents/Develop  |
|                             | er/../Frameworks/IDEFoundation.framework  |
|                             | /Versions/A/IDEFoundation                 |
| legacy_support              | false                                     |
+-----------------------------+-------------------------------------------+

WARN [2020-09-04 15:45:30.25]: Derived content from []
**INFO [2020-09-04 15:45:30.25]: Unable to find any .xccoverage file.
INFO [2020-09-04 15:45:30.25]: Make sure you have enabled 'Gather code coverage' setting on your scheme settings.
INFO [2020-09-04 15:45:30.25]: Alternatively you can provide the full path to your .xccoverage file.**

Any help would be greatly appreciated. Thank you!

### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version: I am using 3.14.2
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

> If you love this fastlane plugin, consider sponsoring it or asking your company to sponsor it. I would really appreciate any
> gesture: https://github.com/sponsors/lyndsey-ferguson. 😍

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by lyndsey-ferguson** [comment] 2020-09-05 14:47
Hello @slanska thank you for using the plugin and for your words of encouragement 😄 .

First, it seems that `xcov` is expecting a `*.xcoverage` file and is not finding it:

```
+-----------------------------+-------------------------------------------+
| Summary for xcov 1.7.2 |
+-----------------------------+-------------------------------------------+
| workspace | Foo.xcworkspace |
| scheme | testCoverage |
| output_directory | fastlane/test_output/xcov_output/ |
| slack_username | fastlane |
| json_report | true |
| markdown_report | true |
| derived_data_path | temp_build_logs/ |
| html_report | true |
| minimum_coverage_percentage | 0 |
| skip_slack | false |
| slack_message | Your xcov coverage report |
| ignore_file_path | ./fastlane/.xcovignore |
| include_test_targets | false |
| only_project_targets | false |
| disable_coveralls | false |
| ideFoundationPath | /Applications/Xcode.app/Contents/Develop |
| | er/../Frameworks/IDEFoundation.framework |
| | /Versions/A/IDEFoundation |
| legacy_support | false |
+-----------------------------+-------------------------------------------+

WARN [2020-09-04 15:45:30.25]: Derived content from []
INFO [2020-09-04 15:45:30.25]: Unable to find any .xccoverage file.
INFO [2020-09-04 15:45:30.25]: Make sure you have enabled 'Gather code coverage' setting on your scheme settings.
INFO [2020-09-04 15:45:30.25]: Alternatively you can provide the full path to your .xccoverage file.
```
According to `xcov's` code for this failure, it tells you to either [enable 'Gather code coverage'](https://github.com/fastlane-community/xcov#requirements) in your scheme settings or provide the full path to that file. Have you done the former? Otherwise, I recommend that you pass the full path to that file.

**Comment by slanska** [comment] 2020-09-06 02:55
Hi @lyndsey-ferguson !
Thanks for the prompt response!

Yes, I did checked those settings:
- 'Gather code coverage' is checked
- I do not think we use xccoverage files, so there should be none (I will double check that).

Note, that xcov works fine with standard scan (before and after using multi_scan), without further changes in the fastlane script nor Xcode project. So, it should be something related to output of multi_scan which is not liked by xcov.

Thanks again!

**Comment by lyndsey-ferguson** [comment] 2020-09-07 12:21
I was guessing from the name of the action you're interested in running, `xcov`, and the docs for that site, that it _needs_ `xccoverage` files. Perhaps the collation is removing them?

Could you set `collate_reports` to `false` in `multi_scan` and re-run your lane?

**Comment by slanska** [comment] 2020-09-08 12:41
As per your suggestion I tried the build with ```collate_reports: false```. Here is what I got:

```
[08:37:34]: ▸ Loading...
[08:37:41]: ▸ xcodebuild: error: Failed to build workspace temporary with scheme Transient Testing.
[08:37:41]: ▸   Reason: Cannot load xctestrun file (/DerivedData/Build/Products/testCoverage_iphonesimulator13.7-x86_64.xctestrun): The file “testCoverage_iphonesimulator13.7-x86_64.xctestrun” couldn’t be opened because there is no such file.
[08:37:41]: ▸   Recovery suggestion: Consult the xctestrun file format documentation using `man xcodebuild.xctestrun`.
xcodebuild: error: Failed to build workspace temporary with scheme Transient Testing.
        Reason: Cannot load xctestrun file (/DerivedData/Build/Products/testCoverage_iphonesimulator13.7-x86_64.xctestrun): The file “testCoverage_iphonesimulator13.7-x86_64.xctestrun” couldn’t be opened because there is no such file.
        Recovery suggestion: Consult the xctestrun file format documentation using `man xcodebuild.xctestrun`.
[08:37:41]: Exit status: 70
```

**Comment by lyndsey-ferguson** [comment] 2020-09-11 12:24
I do not see the same errors:

Fastfile
```
lane :issue_283 do
  multi_scan(
    workspace: File.absolute_path('../AtomicBoy/AtomicBoy.xcworkspace'),
    scheme: 'AtomicBoy',
    try_count: 3,
    output_types: 'json',
    output_files: 'report.json',
    fail_build: false
  )
  xcov(
    workspace: File.absolute_path('../AtomicBoy/AtomicBoy.xcworkspace'),
    scheme: 'AtomicBoy',
    json_report: true,
    markdown_report: true
  )
end
```

```
+--------------------+----+
|      Test Results       |
+--------------------+----+
| Number of tests    | 21 |
| Number of failures | 9  |
+--------------------+----+

[08:20:50]: Scan output types missing 'junit', adding it
[08:20:50]: As output files has one less than the new number of output types, assumming the filename for the junit was missing and added it
[08:20:50]: Scan output types missing 'junit', adding it
[08:20:50]: As output files has one less than the new number of output types, assumming the filename for the junit was missing and added it
[08:20:50]: Scan output types missing 'junit', adding it
[08:20:50]: As output files has one less than the new number of output types, assumming the filename for the junit was missing and added it

+-------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
|                                                                                               multi_scan results                                                                                                |
+-------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+
| result                                                                                          | false                                                                                                         |
| total_tests                                                                                     | 102                                                                                                           |
| passing_testcount                                                                               | 82                                                                                                            |
| failed_testcount                                                                                | 20                                                                                                            |
| failed_tests                                                                                    | ["AtomicBoyUITests/AtomicBoyUITests/testExample", "AtomicBoyUITests/AtomicBoyUITests/testExample18",          |
|                                                                                                 | "AtomicBoyUITests/AtomicBoyUITests/testExample22", "AtomicBoyUITests/AtomicBoyUITests/testExample23",         |
|                                                                                                 | "AtomicBoyUITests/AtomicBoyUITests/testExample31", "AtomicBoyUITests/AtomicBoyUITests/testExample35",         |
|                                                                                                 | "AtomicBoyUITests/AtomicBoyUITests/testExample36", "AtomicBoyUITests/AtomicBoyUITests/testExample41",         |
|                                                                                                 | "AtomicBoyUITests/AtomicBoyUITests/testExample44", "AtomicBoyTests.xctest,                                    |
|                                                                                                 | AtomicBoyUITests/AtomicBoyUITests/testExample19", "AtomicBoyTests.xctest,                                     |
|                                                                                                 | AtomicBoyUITests/AtomicBoyUITests/testExample23", "AtomicBoyTests.xctest,                                     |
|                                                                                                 | AtomicBoyUITests/AtomicBoyUITests/testExample26", "AtomicBoyTests.xctest,                                     |
|                                                                                                 | AtomicBoyUITests/AtomicBoyUITests/testExample3", "AtomicBoyTests.xctest,                                      |
|                                                                                                 | AtomicBoyUITests/AtomicBoyUITests/testExample30", "AtomicBoyTests.xctest,                                     |
|                                                                                                 | AtomicBoyUITests/AtomicBoyUITests/testExample38", "AtomicBoyTests.xctest,                                     |
|                                                                                                 | AtomicBoyUITests/AtomicBoyUITests/testExample4", "AtomicBoyTests.xctest,                                      |
|                                                                                                 | AtomicBoyUITests/AtomicBoyUITests/testExample45", "AtomicBoyTests.xctest,                                     |
|                                                                                                 | AtomicBoyUITests/AtomicBoyUITests/testExample7", "AtomicBoyTests.xctest,                                      |
|                                                                                                 | AtomicBoyUITests/AtomicBoyUITests/testExample8", "AtomicBoyTests.xctest,                                      |
|                                                                                                 | AtomicBoyUITests/AtomicBoyUITests/testExample9"]                                                              |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample.message                           | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample.location                          |          AtomicBoyUITests.m:40                                                                                |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample18.message                         | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample18.location                        |          AtomicBoyUITests.m:176                                                                               |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample22.message                         | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample22.location                        |          AtomicBoyUITests.m:208                                                                               |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample23.message                         | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample23.location                        |          AtomicBoyUITests.m:216                                                                               |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample31.message                         | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample31.location                        |          AtomicBoyUITests.m:280                                                                               |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample35.message                         | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample35.location                        |          AtomicBoyUITests.m:312                                                                               |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample36.message                         | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample36.location                        |          AtomicBoyUITests.m:320                                                                               |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample41.message                         | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample41.location                        |          AtomicBoyUITests.m:360                                                                               |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample44.message                         | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyUITests/AtomicBoyUITests/testExample44.location                        |          AtomicBoyUITests.m:384                                                                               |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample19.message  | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample19.location |           AtomicBoyUITests.m:184                                                                              |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample23.message  | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample23.location |           AtomicBoyUITests.m:216                                                                              |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample26.message  | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample26.location |           AtomicBoyUITests.m:240                                                                              |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample3.message   | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample3.location  |           AtomicBoyUITests.m:56                                                                               |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample30.message  | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample30.location |           AtomicBoyUITests.m:272                                                                              |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample38.message  | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample38.location |           AtomicBoyUITests.m:336                                                                              |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample4.message   | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample4.location  |           AtomicBoyUITests.m:64                                                                               |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample45.message  | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample45.location |           AtomicBoyUITests.m:392                                                                              |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample7.message   | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample7.location  |           AtomicBoyUITests.m:88                                                                               |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample8.message   | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample8.location  |           AtomicBoyUITests.m:96                                                                               |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample9.message   | ((false) is true) failed                                                                                      |
| failure_details.AtomicBoyTests.xctest, AtomicBoyUITests/AtomicBoyUITests/testExample9.location  |           AtomicBoyUITests.m:104                                                                              |
| total_retry_count                                                                               | 11                                                                                                            |
| report_files                                                                                    | ["/Users/lyndsey.ferguson/repo/fastlane-plugin-test_center/fastlane/test_output/AtomicBoyUITests/report.xml"  |
|                                                                                                 | , "/Users/lyndsey.ferguson/repo/fastlane-plugin-test_center/fastlane/test_output/report.xml",                 |
|                                                                                                 | "/Users/lyndsey.ferguson/repo/fastlane-plugin-test_center/fastlane/test_output/AtomicBoyTests/report.xml",    |
|                                                                                                 | "/Users/lyndsey.ferguson/repo/fastlane-plugin-test_center/fastlane/test_output/AtomicBoyUITests/report.json"  |
|                                                                                                 | ,                                                                                                             |
|                                                                                                 | "/Users/lyndsey.ferguson/repo/fastlane-plugin-test_center/fastlane/test_output/AtomicBoyTests/report.json"]   |
+-------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------------------+

[08:20:50]: ------------------
[08:20:50]: --- Step: xcov ---
[08:20:50]: ------------------
[08:20:50]: Skipping file blacklisting as no ignore file was found at path ./fastlane/.xcovignore

+-----------------------------+---------------------------------------------------------------------------------------------------------------+
|                                                           Summary for xcov 1.7.4                                                            |
+-----------------------------+---------------------------------------------------------------------------------------------------------------+
| workspace                   | /Users/lyndsey.ferguson/repo/fastlane-plugin-test_center/AtomicBoy/AtomicBoy.xcworkspace                      |
| scheme                      | AtomicBoy                                                                                                     |
| json_report                 | true                                                                                                          |
| markdown_report             | true                                                                                                          |
| output_directory            | ./fastlane/xcov_report                                                                                        |
| html_report                 | true                                                                                                          |
| minimum_coverage_percentage | 0                                                                                                             |
| skip_slack                  | false                                                                                                         |
| slack_username              | xcov                                                                                                          |
| slack_message               | Your *xcov* coverage report                                                                                   |
| ignore_file_path            | ./fastlane/.xcovignore                                                                                        |
| include_test_targets        | false                                                                                                         |
| only_project_targets        | false                                                                                                         |
| disable_coveralls           | false                                                                                                         |
| ideFoundationPath           | /Applications/Xcode11.6.app/Contents/Developer/../Frameworks/IDEFoundation.framework/Versions/A/IDEFoundatio  |
|                             | n                                                                                                             |
| legacy_support              | false                                                                                                         |
+-----------------------------+---------------------------------------------------------------------------------------------------------------+

[08:20:50]: Resolving Swift Package Manager dependencies...
[08:20:50]: $ xcodebuild -resolvePackageDependencies -workspace /Users/lyndsey.ferguson/repo/fastlane-plugin-test_center/AtomicBoy/AtomicBoy.xcworkspace -scheme AtomicBoy
[08:20:52]: ▸ Command line invocation:
[08:20:52]: ▸     /Applications/Xcode11.6.app/Contents/Developer/usr/bin/xcodebuild -resolvePackageDependencies -workspace /Users/lyndsey.ferguson/repo/fastlane-plugin-test_center/AtomicBoy/AtomicBoy.xcworkspace -scheme AtomicBoy
[08:20:52]: ▸ resolved source packages: 
[08:20:52]: $ xcodebuild -showBuildSettings -workspace /Users/lyndsey.ferguson/repo/fastlane-plugin-test_center/AtomicBoy/AtomicBoy.xcworkspace -scheme AtomicBoy
[08:20:54]: Copying .xccovarchive to ./fastlane/xcov_report/action_0.xccovarchive
[08:20:54]: Copying .xccovreport to ./fastlane/xcov_report/action_0.xccovreport
[08:20:54]: $ /Users/lyndsey.ferguson/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/xcov-1.7.4/lib/xcov-core/bin/xcov-core -s ./fastlane/xcov_report/action_0.xccovreport -o ./fastlane/xcov_report/tmp/report.json20200911-94263-gtbpn1 --ide-foundation-path /Applications/Xcode11.6.app/Contents/Developer/../Frameworks/IDEFoundation.framework/Versions/A/IDEFoundation
[08:20:54]: ▸ Loading...
[08:20:54]: ▸ Opening .xccoverage file at path: /Users/lyndsey.ferguson/repo/fastlane-plugin-test_center/fastlane/xcov_report/action_0.xccovreport
[08:20:54]: ▸ Parsing .xccoverage file...
[08:20:54]: ▸ File successfully parsed
[08:20:54]: ▸ Serializing coverage report...
[08:20:54]: ▸ Report successfully serialized
[08:20:54]: ▸ Writing report on disk...
[08:20:54]: ▸ Coverage report successfully created at path: /Users/lyndsey.ferguson/repo/fastlane-plugin-test_center/fastlane/xcov_report/tmp/report.json20200911-94263-gtbpn1
+---------------+--------+
|  xcov Coverage Report  |
+---------------+--------+
| AtomicBoy.app | 55.08% |
+---------------+--------+


+------+------------+-------------+
|        fastlane summary         |
+------+------------+-------------+
| Step | Action     | Time (in s) |
+------+------------+-------------+
| 1    | multi_scan | 374         |
| 2    | xcov       | 3           |
+------+------------+-------------+

[08:20:54]: fastlane.tools just saved you 6 minutes! 🎉

#######################################################################
# fastlane 2.159.0 is available. You are on 2.151.2.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################

2.159.0 Improvements
* [spaceship] add skip_select_team to Spaceship::ConnectAPI.login (#17215) via Josh Holtz
* [Fastlane.swift] Swift Package Manager support (#16844) via Jorge
* [actions] fixing an issue where last_git_tag command sometimes didn't return the correct tag based on pattern when the commit has multiple tags applied (#17204) via Gligor Kotushevski
* [match] fixed an issue that caused match import command to create wrong names for some provisioning profiles. (#17213) via Nikola Nikolov
* [deliver] fix UploadMetadata taking too long to run (#17169) via Pierluigi D'Andrea
* [snapshot] fix snapshot landscape orientation issue (#17180) via Jari Kalinainen
* [spaceship] fix Spaceship::ConnectAPI.get_app_price_points (#17200) via Josh Holtz

2.158.0 Improvements
* [precheck] migrate to App Store Connect API (except for IAPs) (#17167) via Josh Holtz
* [spaceship] pause, resume and complete a appstore version in phased release (#17165) via polmum

2.157.4 Improvements
* [spaceship][match] fix and improve team selection flow with Spaceship::ConnectAPI client (#17160) via Josh Holtz

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `bundle update fastlane`
```
[xcov_report.zip](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/files/5208890/xcov_report.zip)

**Comment by lyndsey-ferguson** [comment] 2020-09-11 12:26
@slanska can you please put together a sample Xcode project and Fastfile (with `multi_scan` and `xcov`) that reliably reproduces the problem? Once you provide that, I should be able to fix the problem faster.

**Comment by lyndsey-ferguson** [comment] 2020-09-11 12:28
If you're curious, this `issue-283-codecoverage` branch has the work that I did to try and reproduce the issue.

**Comment by slanska** [comment] 2020-09-13 21:14
Hi @lyndsey-ferguson , 
unfortunately I cannot provide info you requested because of NDA. I just can state the following: 1) fragment of my fastlane script is listed above (in my first post) and 2) our project does not use explicit xccoverage file. 

> If you're curious, this issue-283-codecoverage branch has the work that I did to try and reproduce the issue.

I will give it a try.

Thanks for helping me!

**Comment by slanska** [comment] 2020-09-13 21:16
@lyndsey-ferguson , maybe, the following information would be of interest for you: in addition to main project, our workspace also includes notification extension project. Not sure though if this is something that can make a difference at this point.

**Comment by lyndsey-ferguson** [comment] 2020-09-14 22:29
@slanska I need a sample project and `Fastfile`. You can use the AtomicBoy project and 'fastlane/Fastfile` that is part of this plugin ➡️   if you can modify these files so that I can reproduce this issue, then I can proceed with the investigation into this issue.

To be absolutely clear: I do not need your actual project, so there is no need to discuss an NDA since you would be modifying the code that I have already provided you in this plugin.

Regarding the other note you provided about a notification extension: it will have its own target as well. Have you enabled code coverage for all targets, or some targets (and excluded this notification?)
<img width="578" alt="Screen Shot 2020-09-14 at 6 29 39 PM" src="https://user-images.githubusercontent.com/5741516/93144561-44fbf600-f6b8-11ea-8660-fab6f9b09b6b.png">

**Comment by lyndsey-ferguson** [comment] 2020-09-14 22:30
If we cannot figure this out, and I don't have a way of reproducing the issue, I will have to close this issue. I typically wait 2 weeks to give you time to provide something before I close the issue.

**Comment by lyndsey-ferguson** [comment] 2020-09-27 19:44
I cannot duplicate the problem. If a sample project is provided, I can re-open this Issue. Please consider providing one so I can fix the bug!
# 🙏

**Closed by lyndsey-ferguson** 2020-09-27 19:44 UTC
Labels: ♻️ multi_scan, 🐞bug, 👋Consider closing Friday
