### ISSUE TITLE
prelaunch_simulator error with two multi_scan runs

### ISSUE THREAD

**Issue by thuyvu113** [lyndsey-ferguson/fastlane-plugin-test_center#192] opened 2020-02-16 20:31 UTC
Thank you for the awesome plugin!

I tried to run two multi_scan in two separated lanes like this:

```
private_lane :ui_test do |options|
    lane1()
    lane2()
end

private_lane :lane1 do |options|
    multi_scan(...,prelaunch_simulator: false)
end

private_lane :lane2 do |options|
    multi_scan(...,prelaunch_simulator: false)
end
```

The problem is that the first `multi_scan` in `lane1` works smoothly . However, when the `multi_scan` in `lane2` ran, I got an error `prelaunch_simulator' value must be either 'true' or 'false'! Found String instead.`

I also set `FASTLANE_EXPLICIT_OPEN_SIMULATOR` in my env but it still doesn't work.

**Comment by lyndsey-ferguson** [comment] 2020-02-21 14:37
Can you please include the entire log using the `--verbose` flag?

**Comment by lyndsey-ferguson** [comment] 2020-03-11 22:02
Closing due to an inability to reproduce/debug

**Closed by lyndsey-ferguson** 2020-03-11 22:02 UTC
Labels: Consider closing Friday, ♻️ multi_scan, 🐞bug
