### ISSUE TITLE
cannot run on  multiple devices using fastlane multi_scan

### ISSUE THREAD

**Issue by ishammoho** [lyndsey-ferguson/fastlane-plugin-test_center#187] opened 2020-01-15 04:11 UTC
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the example [Fastfile](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/fastlane/Fastfile)
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

### Issue Description
Currently we are using scan to run auto test on multiple physical devices, lane looks something  like this

```
 iPadPro = "platform=iOS,id=234324324234"
   iPhone7 = "platform=iOS,id=187638264832648234"
    
    # Excute on devices:
    devices = [iPhone7, iPadPro]

 scan(
        scheme:                 "Automation",
        # This is local to the project dir so that these don't collide in CI
        buildlog_path:          "./scan-auto-logs",
        only_testing:           test_classes,
        result_bundle:          true,
        destination:            devices,
        output_types:           "junit",
        fail_build:             false
      )
````

However when I try this using multi_scan it runs test only on the first devices in the devices array. In above example it runs only in the iPhone7. Just wondering how could I pass multiple devices. 

Thanks

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by lyndsey-ferguson** [comment] 2020-01-15 21:23
@ishammoho could you include the logs of the fastlane when you include the `--verbose` flag? I'd like to see what is happening.

Also, to make sure I don't miss anything when trying to reproduce this issue on my end, could you provide a sample of how you are calling `multi_scan` in the `Fastfile`?

**Comment by ishammoho** [comment] 2020-01-15 21:45
Thanks @lyndsey-ferguson 
```
DEBUG [2020-01-16 10:39:46.23]: Removing pre-existing test_result bundles:
DEBUG [2020-01-16 10:39:46.23]:   /Users/isham/workspace/ios/fastlane/test_output/Automation.test_result
INFO [2020-01-16 10:39:46.23]: Starting test run 1
DEBUG [2020-01-16 10:39:46.23]: Deleting xcresults:
DEBUG [2020-01-16 10:39:46.23]: Restarting Simulator 00008027
DEBUG [2020-01-16 10:39:46.82]: Restarting Simulator 876deee48648823ca8ff7d2e59d913dc39e897e9
INFO [2020-01-16 10:39:47.49]: Starting scan #1 with 90 tests for batch #1.
DEBUG [2020-01-16 10:39:47.49]: retrying_scan #update_scan_options
DEBUG [2020-01-16 10:39:47.49]: 	Setting scheme to Automation
DEBUG [2020-01-16 10:39:47.49]: 	Setting result_bundle to true
DEBUG [2020-01-16 10:39:47.49]: 	Setting fail_build to false
DEBUG [2020-01-16 10:39:47.49]: 	Setting destination to ["platform=iOS,id=00008027-000458802185002E", "platform=iOS,id=876deee48648823ca8ff7d2e59d913dc39e897e9"]
DEBUG [2020-01-16 10:39:47.49]: 	Setting prelaunch_simulator to false
DEBUG [2020-01-16 10:39:47.49]: 	Setting workspace to ANZ.xcworkspace
DEBUG [2020-01-16 10:39:47.49]: 	Setting skip_detect_devices to false
DEBUG [2020-01-16 10:39:47.49]: 	Setting reset_simulator to false
DEBUG [2020-01-16 10:39:47.49]: 	Setting reinstall_app to false
DEBUG [2020-01-16 10:39:47.49]: 	Setting app_identifier to nz.co.anz.goMoneynz
DEBUG [2020-01-16 10:39:47.49]: 	Setting only_testing to[........]


                                                                       Summary for scan 2.134.0                                                                       |
+------------------------------------------------+---------------------------------------------------------------------------------------------------------------------+
| scheme                                         | Automation                                                                                                          |
| result_bundle                                  | true                                                                                                                |
| fail_build                                     | false                                                                                                               |
| prelaunch_simulator                            | false                                                                                                               |
| workspace                                      | XXX.xcworkspace                                                                                                     |
| skip_detect_devices                            | false                                                                                                               |
| force_quit_simulator                           | false                                                                                                               |
| reset_simulator                                | false                                                                                                               |
| reinstall_app                                  | false                                                                                                               |
| app_identifier                                 | xx.xx.xxx.                                                                                                |
| only_testing [....]

 xctestrun                                      | ./DerivedData/Build/Products/Automation_iphoneos13.0-arm64e.xctestrun                                               |
| clean                                          | false                                                                                                               |
| open_report                                    | false                                                                                                               |
| output_directory                               | /Users/isham/workspace/ios/fastlane/test_output/ANZUITests-batch-1                                                  |
| output_files                                   | report.junit                                                                                                        |
| buildlog_path                                  | ~/Library/Logs/scan                                                                                                 |
| include_simulator_logs                         | false                                                                                                               |
| derived_data_path                              | ./DerivedData                                                                                                       |
| should_zip_build_products                      | false                                                                                                               |
| use_clang_report_name                          | false                                                                                                               |
| disable_concurrent_testing                     | true                                                                                                                |
| skip_build                                     | false                                                                                                               |
| xcargs                                         | 'CLIENT_IDLE_TIME=20' 'REQUEST_TIMEOUT=5' -parallel-testing-enabled NO                                              |
| slack_use_webhook_configured_username_and_icon | false                                                                                                               |
| slack_username                                 | fastlane                                                                                                            |
| slack_icon_url                                 | https://s3-eu-west-1.amazonaws.com/fastlane.tools/fastlane.png                                                      |
| skip_slack                                     | true                                                                                                                |
| slack_only_on_failure                          | false                                                                                                               |
| xcodebuild_command                             | env NSUnbufferedIO=YES xcodebuild                                                                                   |
| output_types                                   | junit                                                                                                               |
| xcode_path                                     | /Applications/Xcode.app                                                                                             |
| build_for_testing                              | false

 Loading...
INFO [2020-01-16 10:39:49.49]: ▸ 2020-01-16 10:39:49.495 xcodebuild[94988:5975912]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
INFO [2020-01-16 10:39:49.49]: ▸ /Users/dsds/workspace/ios/fastlane/test_output/XXXUITests-batch-1/Automation.test_result/Staging/1_Test/Diagnostics/ANZUITests-0E308A23-95EE-413E-AAC9-991DAAB0A2C8/XXXUITests-A0DF65D5-6218-49C8-95A4-BD4C2EDC1141/Session-XXXUITests-2020-01-16_103949-d8M8nU.log
INFO [2020-01-16 10:39:49.49]: ▸ 2020-01-16 10:39:49.497 xcodebuild[94988:5975877] [MT] IDETestOperationsObserverDebug: (484E7086-0F5A-4670-8BCD-9E2D0F5D4C58) Beginning test session XXXUITests-484E7086-0F5A-4670-8BCD-9E2D0F5D4C58 at 2020-01-16 10:39:49.497 with Xcode 11A420a on target 📱<DVTiOSDevice (0x7fd099e70070), WGN iPad Pro Silver 2, iPad, 13.1 (17A844), 00008027-000458802185002E> {
```

fastlane looks like this

```
 desc "Run diversity suite"
  lane :run_automation do |options|
    set_scan_xcargs

    FileUtils.rm_rf("../fastlane/test_output") if File.exist? "../fastlane/test_output"

    # Device Pool 
    # use id=UDID for reliablity
    iPadPro = "platform=iOS,id=00008027-213..."
    iPhone7 = "platform=iOS,id=123123123123213213...."
    
    # Excute on devices:
    devices = [iPadPro,iPhone7]

    begin
      test_run_block = lambda do |testrun_info| 
        failed_test_count = testrun_info[:failed].size
        
        if failed_test_count > 0
          UI.important('The run of tests would finish with failures due to fragile tests here.')
    
          try_attempt = testrun_info[:try_count]
          if try_attempt < 3
            UI.header('Since we are using :multi_scan, we can re-run just those failing tests!')
          end
        end
      end
      
    begin
      multi_scan(
        scheme:                  "Automation",
        try_count:               3,
        result_bundle:           true,
        testrun_completed_block: test_run_block,
        fail_build:              false,
        destination:             devices,
        prelaunch_simulator:     false
      )

      xchtmlreport(
        result_bundle_path: "fastlane/test_output/Automation.test_result", 
        enable_junit: true
      )
    rescue => ex
      # Logs error instead of failing build
      UI.error(ex)
    ensure
      collect_build_artifacts(
        source_path: "fastlane/test_output/",
        target_path: "automation_tests/app-gomoney"
      )
    end
    end
    
  end
```

**Comment by lyndsey-ferguson** [comment] 2020-02-21 22:50
@ishammoho actually, I need to see more logs. It is easiest for me to get the complete log. You can remove sensitive data such as API keys, token values, test names, product names, but leave the data that includes what `xcodebuild` command is doing, what the results are from calling that command, any stack traces of crashes, etc.

**Comment by lyndsey-ferguson** [comment] 2020-03-11 22:03
Closing due to an inability to reproduce/debug

**Closed by lyndsey-ferguson** 2020-03-11 22:03 UTC
Labels: Consider closing Friday, 🐞bug, 🔎 under investigation, 🙏 help wanted
