### ISSUE TITLE
REXML::ParseException: #<RuntimeError: Illegal character '&' in raw string

### ISSUE THREAD

**Issue by v-ahadke** [lyndsey-ferguson/fastlane-plugin-test_center#100] opened 2019-05-13 13:28 UTC
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

### Issue Description
I am using `multi_scan` action to run the KIF UITests. When the test report xml file contains special symbold like `<`, `<`,`&` etc , multi_scan fails with error mentioned in details.

### Expected behavior: 
It should handle special symbols correctly & parse the xml file correctly.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
REXML::ParseException: #RuntimeError: Illegal character '&' in raw string "XCTAssertTrue failed - Expected text is 'Ultimate Colosseum Arena & Exclusive Borghese Gallery Tour', actual text is 'Optional("Germaine\'s Hawaiian Luau")'">
/usr/local/Cellar/ruby@2.3/2.3.6_3/lib/ruby/2.3.0/rexml/text.rb:156:in `block in check'
/usr/local/Cellar/ruby@2.3/2.3.6_3/lib/ruby/2.3.0/rexml/text.rb:154:in `scan'
/usr/local/Cellar/ruby@2.3/2.3.6_3/lib/ruby/2.3.0/rexml/text.rb:154:in `check'
/usr/local/Cellar/ruby@2.3/2.3.6_3/lib/ruby/2.3.0/rexml/text.rb:121:in `initialize'
/usr/local/Cellar/ruby@2.3/2.3.6_3/lib/ruby/2.3.0/rexml/parsers/treeparser.rb:47:in `new'
/usr/local/Cellar/ruby@2.3/2.3.6_3/lib/ruby/2.3.0/rexml/parsers/treeparser.rb:47:in `parse'
/usr/local/Cellar/ruby@2.3/2.3.6_3/lib/ruby/2.3.0/rexml/document.rb:288:in `build'
/usr/local/Cellar/ruby@2.3/2.3.6_3/lib/ruby/2.3.0/rexml/document.rb:45:in `initialize'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-plugin-test_center-3.6.3/lib/fastlane/plugin/test_center/actions/collate_html_reports.rb:34:in `new'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-plugin-test_center-3.6.3/lib/fastlane/plugin/test_center/actions/collate_html_reports.rb:34:in `block in opened_reports'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-plugin-test_center-3.6.3/lib/fastlane/plugin/test_center/actions/collate_html_reports.rb:30:in `map'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-plugin-test_center-3.6.3/lib/fastlane/plugin/test_center/actions/collate_html_reports.rb:30:in `opened_reports'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-plugin-test_center-3.6.3/lib/fastlane/plugin/test_center/actions/collate_html_reports.rb:9:in `run'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-plugin-test_center-3.6.3/lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb:172:in `collate_html_reports'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-plugin-test_center-3.6.3/lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb:107:in `collate_reports'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-plugin-test_center-3.6.3/lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb:92:in `scan_testable'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-plugin-test_center-3.6.3/lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb:43:in `block in scan'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-plugin-test_center-3.6.3/lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb:42:in `each'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-plugin-test_center-3.6.3/lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb:42:in `scan'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-plugin-test_center-3.6.3/lib/fastlane/plugin/test_center/actions/multi_scan.rb:23:in `run'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/other_action.rb:23:in `method_missing'
/MyApp/fastlane/actions/run_kif_ui_tests_rerun_multi_scan.rb:41:in `kif_ui_tests_rerun_multi_scan'
/MyApp/fastlane/actions/run_kif_ui_tests_rerun_multi_scan.rb:6:in `run'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
Fastfile:76:in `block (2 levels) in parsing_binding'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/lane.rb:33:in `call'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
/MyApp/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
/MyApp/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
/MyApp/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
/MyApp/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
/MyApp/vendor/bundle/ruby/2.3.0/gems/fastlane-2.121.1/bin/fastlane:23:in `<top (required)>'
/MyApp/vendor/bundle/ruby/2.3.0/bin/fastlane:22:in `load'
/MyApp/vendor/bundle/ruby/2.3.0/bin/fastlane:22:in `<top (required)>'
/MyApp/vendor/gem/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `load'
/MyApp/vendor/gem/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/MyApp/vendor/gem/gems/bundler-1.17.3/lib/bundler/cli/exec.rb:28:in `run'
/MyApp/vendor/gem/gems/bundler-1.17.3/lib/bundler/cli.rb:463:in `exec'
/MyApp/vendor/gem/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/MyApp/vendor/gem/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/MyApp/vendor/gem/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/MyApp/vendor/gem/gems/bundler-1.17.3/lib/bundler/cli.rb:27:in `dispatch'
/MyApp/vendor/gem/gems/bundler-1.17.3/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/MyApp/vendor/gem/gems/bundler-1.17.3/lib/bundler/cli.rb:18:in `start'
/MyApp/vendor/gem/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
/MyApp/vendor/gem/gems/bundler-1.17.3/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/MyApp/vendor/gem/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
./vendor/gem/bin/bundle:22:in `load'
./vendor/gem/bin/bundle:22:in `<main>'
</pre>
</details>

### Environment

<details>
  <pre>result = other_action.multi_scan(
          workspace: "TestMultiScan.xcworkspace",
          try_count: options[:retry],
          fail_build: true,
          scheme: options[:scheme],
          device: "iPhone 8",
          output_directory: "./../build",
          buildlog_path: "./../build/logs/scan",
          output_types: "html,junit",
          output_files: "#{report_file_name}.html,#{report_file_name}.xml",
          only_testing: options[:tests_to_run],
          testrun_completed_block: test_run_block
        )</pre>
</details>

**Comment by lyndsey-ferguson** [comment] 2019-05-13 15:02
Thank you for the bug report. It may be a while until I can fix this, but as a work-around, you could add [this](https://stackoverflow.com/a/17237801/71877) code to your `test_run_block` to _repair_ the HTML so that `REXML` can parse it.

**Comment by v-ahadke** [comment] 2019-05-13 15:32
@lyndsey-ferguson Thanks for your reply. Actually I am facing this issue for junit report file (xml) instead of HTML. My `test_run_block` look like below 
```
test_run_block = lambda do |testrun_info|
          failed_test_count = testrun_info[:failed].size  
          if failed_test_count > 0
            (flaky_test_list << testrun_info[:failed]).flatten!
            UI.important('The run of tests would finish with failures due to fragile tests here.')

            try_attempt = testrun_info[:try_count]
            if try_attempt < options[:retry].to_i
              UI.header('Since we are using :multi_scan, we can re-run just those failing tests!')
            else
              UI.error("Tests failed")
            end
          else
            UI.success("All tests passed successfully")
          end
        end
```
AFAIK, generating collate junit report happens inside collage_junit.rb file, can you please explain where do we need to add the code from stackoverflow link in above block? Thanks

**Comment by lyndsey-ferguson** [comment] 2019-05-13 15:43
Sorry, I updated my suggestion to state "Junit XML" instead of HTML. I would put the code anywhere in the block (it is called after each test_run, before _any_ collation of the Junit files).
```ruby
# get the file path
report_filepath = File.absolute_path(testrun_info[:report_filepath])

# read the file and "fix" the content
content = File.open(report_filepath, "r:iso-8859-1:utf-8").read
content.gsub!(/&(?!(?:amp|lt|gt|quot|apos);)/, '&amp;')

# write the file with the "fixed" content
File.open(report_filepath, 'w') { |file| file.write(content) }
```

**Comment by v-ahadke** [comment] 2019-05-15 06:41
Hey @lyndsey-ferguson , above workaround worked for me. Thank you very much 👍 . Do we have any ETA on fixing the issue in plugin itself?

**Comment by lyndsey-ferguson** [comment] 2019-05-15 11:14
With regards to an ETA, it may be a few months before I can get to it. I am open to PRs if you want to fix it and add the tests. I would suggest adding the above code as a function in [`Fastlane::Actions:: CollateJunitReportsAction`](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/lib/fastlane/plugin/test_center/actions/collate_junit_reports.rb).

You could do something similar to what I did in [`Fastlane::Actions::CollateHtmlReportsAction`](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/lib/fastlane/plugin/test_center/actions/collate_html_reports.r), and create a [`opened_reports` function](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/lib/fastlane/plugin/test_center/actions/collate_html_reports.rb#L29) that tries to open the file(s), and if one fails with an REXML exception, it tries to fix it and then re-open it.

**Comment by lyndsey-ferguson** [comment] 2019-07-26 00:31
@v-ahadke can you include a sample of a test that causes this issue? I can duplicate it for the HTML report, but not Junit.
Thanks

**Comment by v-ahadke** [comment] 2019-07-26 12:03
Hi @lyndsey-ferguson , you can use any UITests which will fail & failure reason should include special symbol `&` as added in details of issue 
`Illegal character '&' in raw string "XCTAssertTrue failed - Expected text is 'Ultimate Colosseum Arena & Exclusive Borghese Gallery Tour', actual text is 'Optional("Germaine\'s Hawaiian Luau")'"`

**Comment by lyndsey-ferguson** [comment] 2019-08-03 20:41
I have not been able to reproduce this issue for the junit reports. The ampersands are escaped correctly.

I am using `xcpretty` `v0.3.0`, which version are you using?

**Comment by lyndsey-ferguson** [comment] 2019-08-15 01:23
I'm closing this issue as I cannot reproduce it and I do not have any sample of a reproducible case.

**Closed by lyndsey-ferguson** 2019-08-15 01:23 UTC
Labels: 🐞bug, 🔸collate_junit_reports
